//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursMıx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersProgram
    {
        public int id { get; set; }
        public Nullable<int> DersID { get; set; }
        public Nullable<int> SınıfID { get; set; }
        public Nullable<int> ÖgrenciGrupID { get; set; }
        public string GünlükDersSayısı { get; set; }
        public Nullable<int> GünlerID { get; set; }
    
        public virtual Grup Grup { get; set; }
    }
}
