//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursMıx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersProgramHaftalık
    {
        public int id { get; set; }
        public Nullable<int> SınıfID { get; set; }
        public string BaşlangıcZamanı { get; set; }
        public string Çalışma_Saatleri { get; set; }
        public string Pazartesi { get; set; }
        public string Salı { get; set; }
        public string Carşamba { get; set; }
        public string Perşembe { get; set; }
        public string Cuma { get; set; }
        public string Cumartesi { get; set; }
        public string Pazar { get; set; }
    }
}
