//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursMıx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersProgramMVC
    {
        public int id { get; set; }
        public Nullable<int> SınıfID { get; set; }
        public string DERS { get; set; }
        public string SINIF { get; set; }
        public string Günler { get; set; }
        public string BaşlangıcZamanı { get; set; }
        public string BitişZamanı { get; set; }
    }
}
