//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursMıx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EKurum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EKurum()
        {
            this.Kampus = new HashSet<Kampu>();
        }
    
        public int id { get; set; }
        public string KurumName { get; set; }
        public Nullable<System.DateTime> KurumTarihi { get; set; }
        public string Telefon { get; set; }
        public string Faks { get; set; }
        public string Adres { get; set; }
        public Nullable<int> IL { get; set; }
        public Nullable<int> ILCE { get; set; }
        public Nullable<int> Semt { get; set; }
        public string EPosta { get; set; }
        public string EWeb { get; set; }
        public string VDAIRE { get; set; }
        public string CVERGINO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kampu> Kampus { get; set; }
    }
}
