//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursMıx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Görüsler
    {
        public int id { get; set; }
        public string Görüs { get; set; }
        public Nullable<int> OlusturanKisi { get; set; }
        public Nullable<System.DateTime> mas_crdate { get; set; }
        public string SISKODU { get; set; }
    }
}
