//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursMıx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILCE
    {
        public int id { get; set; }
        public string IlceName { get; set; }
        public Nullable<int> ILID { get; set; }
    
        public virtual IL IL { get; set; }
    }
}
