//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursMıx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kampu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kampu()
        {
            this.FizikselYers = new HashSet<FizikselYer>();
            this.Okuls = new HashSet<Okul>();
        }
    
        public int id { get; set; }
        public string YerleskName { get; set; }
        public string YerleskeShortName { get; set; }
        public string Lokasyon { get; set; }
        public Nullable<System.DateTime> Kurulus { get; set; }
        public Nullable<int> KurumID { get; set; }
    
        public virtual EKurum EKurum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FizikselYer> FizikselYers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Okul> Okuls { get; set; }
    }
}
