//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursMıx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Okul
    {
        public int id { get; set; }
        public Nullable<int> OkulTip { get; set; }
        public string OkulAdı { get; set; }
        public string YetkiliName { get; set; }
        public string YetkiliTel { get; set; }
        public string YetkiliMaıl { get; set; }
        public Nullable<int> KampusID { get; set; }
    
        public virtual Kampu Kampu { get; set; }
    }
}
