//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursMıx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organızasyon
    {
        public int ID { get; set; }
        public string OrgAdı { get; set; }
        public string OrgURL { get; set; }
        public string OrgILETISIM { get; set; }
        public string OrgMAIL { get; set; }
    }
}
