//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursMıx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramView
    {
        public int id { get; set; }
        public string ProgramName { get; set; }
        public string ProgramCode { get; set; }
        public Nullable<int> DepartmanID { get; set; }
        public string DepartmanName { get; set; }
        public string Durumu { get; set; }
    }
}
