//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursMıx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ögrenci
    {
        public int OgrID { get; set; }
        public Nullable<int> SeviyeID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> KursID { get; set; }
        public string TC { get; set; }
        public string Cinsiyet { get; set; }
        public string CepTel { get; set; }
        public string Veli { get; set; }
        public string DogumTarıhı { get; set; }
        public string DogumYerı { get; set; }
        public string Emaıl { get; set; }
        public string BabaAd { get; set; }
        public string BabaCep { get; set; }
        public string BabaMeslek { get; set; }
        public string AnneAd { get; set; }
        public string AnneCep { get; set; }
        public string AnneMeslek { get; set; }
        public string Adres { get; set; }
        public string Okul { get; set; }
        public Nullable<int> ReferansID { get; set; }
        public Nullable<int> YüzdePay { get; set; }
    
        public virtual Grup Grup { get; set; }
        public virtual KursTür KursTür { get; set; }
        public virtual Referan Referan { get; set; }
    }
}
